services:
  app:
    image: nodejs-app:latest
    environment:
      - CONNECTION_STRING=mongodb://host.docker.internal:27017/project_node
      - LOG_LEVEL=info
      - EXPIRE_TIME=84000
      - FILE_UPLOAD_PATH=/data/uploads
    ports:
      - 3000:3000